// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro', // Introduction page at the top
    {
      type: 'autogenerated',
      dirName: '.', // This will auto-generate the sidebar from the docs/ directory structure
    },
  ],
  moduleSidebar: [
    {
      type: 'category',
      label: 'Module 1: ROS 2 Fundamentals',
      items: [
        {
          type: 'autogenerated',
          dirName: '01-ros2',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin',
      items: [
        {
          type: 'autogenerated',
          dirName: '02-digital-twin',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac Sim',
      items: [
        {
          type: 'autogenerated',
          dirName: '03-nvidia-isaac',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA) System',
      items: [
        {
          type: 'autogenerated',
          dirName: '04-vla',
        },
      ],
    },
  ],
};

module.exports = sidebars;